//
//  VCLiterals.swift
//  RoyoConsultantVendor
//
//  Created by Sandeep Kumar on 27/05/20.
//  Copyright © 2020 SandsHellCreations. All rights reserved.
//

import Foundation

enum VCLiteral: String {
    case FACEBOOK
    case GOOGLE
    case LOGIN_USING_EMAIL
    case LOGIN_USING_MOBILE
    case SIGNUP_WITH_PHONE
    case SIGNUP_WITH_EMAIL
    case LETS_GET_STARTED
    case NEW_USER
    case SIGNUP
    case LOGIN_EMAIL_DESC
    case EMAIL_PLACEHOLDER
    case PSW_PLACEHOLDER
    case FORGOT_PASSWORD
    case NO_ACCOUNT
    case MOBILE_PACEHOLDER
    case LOGIN_USING_MOBILE_DESC
    case NAME_PLACEHOLDER
    case DOB_PLACEHOLDER
    case ReEnterPsw_PLACEHOLDER
    case BIO_PLACEHOLDER
    case ALREADY_REGISTER
    case LOGIN
    case BY_SIGNING_UP
    case TERMS
    case AND
    case PRIVACY
    case VERIFICATION
    case VERIFICATION_DESC
    case CODESENT
    case CODE_NOT_RECEIVED
    case RESEND_CODE
    case CANCEL
    case OK
    case NAME_PREFIX_MR
    case NAME_PREFIX_MRS
    case NAME_PREFIX_DR
    case NAME_PREFIX_MISS
    case UPLOAD_ERROR
    case RETRY_SMALL
    case RETRY
    case JOINCONSULTANTS
    case CATEGORY_VC_TITLE
    case CATEGORY_VC_SUBTITLE
    case SUBCATEGORY_TITLE
    case DONE
    case SET_PREFERENCES_TITLE
    case SET_PREFERENCES_VALIDATION_ALERT_MULTI
    case SET_PREFERENCES_VALIDATION_ALERT_SINGLE
    case SERVICE_TYPE_TITLE
    case NEXT
    case CONSULTATION_FEE
    case FOR_UNIT
    case FIXED_PRICE
    case PRICE_RANGE
    case ADD_AVAILABILITY
    case MANAGE_AVAILABILITY
    case EDIT_AVAILABILITY
    case SELECT_AVAILABILITY
    case WEEK_DAYS
    case SELECT_DATE
    case NEW_INTERVAL
    case FROM
    case TO
    case ALL_WEEKDAYS
    case FOR_DATE
    case FOR_DAY
    case SAVE
    case SUN
    case MON
    case TUE
    case WED
    case THU
    case FRI
    case SAT
    case NEW_INTERVAL_ALERT
    case SLOT_ALERT_SAVE
    case SERVICE_ALERT
    case NA
    case WALLET
    case AVAILABLE_BALANCE
    case TRANSACTION_HISTORY
    case PAYOUT
    case WALLET_NO_DATA
    case WALLET_NO_DATA_DESC
    case RECEIVED_FROM
    case INPROGRESS
    case ACCEPT
    case COMPLETE
    case NO_ANSWER
    case BUSY
    case FAILED
    case NEW
    case ALL
    case REQUESTS
    case CANCELLED
    case NO_REQUESTS
    case START
    case ACCEPT_TITLE
    case ACCEPT_REQUEST
    case ACCEP_REQUEST_ALERT_DESC
    case START_REQUEST
    case START_REQUEST_ALERT_DESC
    case CHAT
    case CLASSES
    case NOTIFICATIONS
    case INVITE_PEOPLE
    case CONTACT_US
    case TERMS_AND_CONDITIONS
    case ABOUT
    case LOGOUT
    case AGE
    case PROFILE
    case VERSION
    case VERSION_INFO
    case LOGOUT_ALERT_MESSAGE
    case CANCEL_REQUEST
    case CANCEL_REQUEST_ALERT_MESSAGE
    case PHOTO
    case CHAT_THREAD_TIME
    case END_CHAT
    case END_CHAT_MESSAGE
    case CHAT_INITIAL_MESSAGE
    case CANT_SEND_MESSAGE
    case EDIT_CAPS
    case CLIENTS_TITLE
    case EXPERIENCE
    case REVIEWS
    case REVIEW
    case MANAGE_AVAIL
    case MANAGE_PREFE
    case UPDATE_CAT
    case YR_EXP
    case YRS_EXP
    case PHONE_NUMBER
    case EDIT_PROFILE
    case NO_CLASSES_DATA
    case NO_CLASSES_DATA_DESC
    case CLASS_CATEGORY
    case USER_JOINED
    case START_CLASS
    case COMPLETE_CLASS
    case START_CLASS_ALERT
    case COMPLETE_CLASS_ALERT
    case ADD_NEW
    case ADD_CLASS
    case SELECT_CATEGORY
    case CLASS_NAME
    case SELECT_TIME
    case PRICE_OF_CLASS
    case NETWORK_ERROR
    case NO_REQUESTS_DESC
    case ACCOUNT_NOT_APPROVED
    case ACCOUNT_NOT_APPROVED_DESC
    case ACCOUNT_REJECTED_DESC
    case REVENUE
    case APPOINTMENTS
    case COMPLTED_APPTS
    case FAILED_APPTS
    case TOTAL_REVENUE
    case CALLING
    case INCOMING
    case RINGING
    case CALL_CANCELLED
    case CHAT_NO_DATA
    case CHAT_NO_DATA_DESC
    case MINUTE
    case MINUTES
    case SECOND
    case SECONDS
    case NOTIFICATION_NO_DATA
    case NOTIFICATION_NO_DATA_DESC
    case CALL
    case FORGOT_PSW_MESSAGE
    case PASSWORD_RESET_MESSAGE
    case BANK_DETAILS
    case ACCOUNT_NUMBER
    case ACCOUNT_NAME
    case IFSC_CODE
    case MONEY_SENT_TO_BANK
    case ADDED_TO_WALLET
    case BANK_NAME
    case TOTAL_SERVICES
    case ADD_MONEY
    case DEBIT_CARD
    case CREDIT_CARD
    case GPAY
    case BHIM
    case CARD_ENDING_WITH
    case PAY_AMOUNT
    case INVALID_AMOUNT
    case CARD_EXP_PLACEHOLDER
    case EDIT
    case DELETE
    case EDIT_CARD
    case INPUT_AMOUNT
    case UPDATE
    case DELETE_CARD_MESSAGE
    case ADD
    case UPLOAD_DOCS
    case TITLE
    case DESC
    case DOC_UPLOADING_ALERT
    case ADD_ONE_DOC_ALERT
    case BLOGS
    case POST_ARTICLE
    case POST_BLOG
    case ARTICLES
    case VIEWS
    case VIEW
    case APPOINTMENT
    case VIEW_ALL
    case VIEW_PRESCRIPTION
    case ADD_PRESC
    case EDIT_DIGITAL_PRESC
    case DIGITAL_PRESCRIPTION
    case MANUAL_PRESCRIPTION
    case PATIENT
    case RECORD_DETAILS
    case RECORD_TITLE
    case ADD_IMAGES
    case RECORD_TITLE_ALERT
    case PRESCRIPTION_IMAGE_ALERT
    case RESET
    case MEDICINE_NAME
    case DURATION
    case DOSAGE_TYPE
    case DOSAGE_TIMINGS
    case PRESCRIPTION_NOTES
    case PRESCRIPTIONS
    case ADD_DIGITAL_PRESC
    case MEDICINE_ALERT
    case DURATION_ALERT
    case DOSAGE_ALERT
    case DOSAGE_TIMING_ALERT
    case MEDICINCE_DONE_ALERT
    case ADD_MANUAL_PRESC
    case EDIT_MANUAL_PRESC
    case UPLOAD_BANNER
    case SUBMIT
    case FAVOURITES
    case CREATE_ACCOUNT_TO_CONTINUE
    case BY_CONTINUE
    case ALREADY_ACCOUNT
    case LOGIN_WITH
    case QUALIFICATIONS
    case GENDER
    case CHOOSE_LANG
    case QUALIFICATION_ALERT
    case GENDER_ALERT
    case LANGUAGE_ALERT
    case GET_STARTED
    case ALLOW_LOCATION
    case ALLOW_LOCATION_DESC
    case USE_MY_LOCATION
    case SKIP_FOR_NOW
    case REACHED
    case SERVICE_STARTED
    case TRACK_STATUS
    case CANCEL_SERVICE
    case START_SERVICE
    case REACHED_DEST_TITLE
    case FREE_EXPERT_ADVICE
    case NO_QUESTIONS
    case NO_QUESTIONS_DESC
    case DETAILS
    case ANSWER
    case ANSWERS
    case ADVICE_HERE
    case SECOND_OPINION
    case All_SMALL
    case HISTORY
    case NO_HISTORY
    case NO_HISTORY_DESC
    case DATE
    case TIME
    case VIEW_MAP
    case ACCOUNT_SETTINGS
    case CHANGE_PASSWORD
    case CHANGE_LANGUAGE
    case OLD_PSW
    case NEW_PSW
    case CONFIRM_PSW
    case PRESC_DETAIL
    case Appointment_Date
    case Services
    case Amount
    case Prescription
    case RESET_DATE
    case DOC_MESSAGE
    case DOC_TITLE
    case UPDATE_PHONE_NUMBER
    case CHOOSE_APP_TITLE
    case CHOOSE_APP_OPTION_PATIENT
    case CHOOSE_APP_OPTION_DOCTOR
    case TYPING
    case LANGUAGE_ENGLISH
    case LANGUAGE_ARABIC
    case CHOOSE_LANGUAGE
    case MANAGE_DOCS
    case TAB_HOME
    case TAB_WALLET
    case TAB_REVENUE
    case TAB_PROFILE
    case UPDATE_TITLE
    case UPDATE_DESC
    case SYMPTOMS
    case MEDICAL_RECORD
    case PRICE
    case NATIONALITY
    case VIEW_DETAIL
    case NO_ARTICLES
    case NO_ARTICLES_DESC
    case NO_BLOGS
    case NO_BLOGS_DESC
    case AUDIO
    case PROTIEN_INTAKE
    case PROTIEN_GMS
    case TAKE_PROTIEN
    case PROTIEN_INTAKE_IN_GRAMS
    case SET_DAILY_PROTIEN_LIMIT
    case ADD_DAILY_PROTEIN_LIMIT
    case SET_DAILY_LIMIT
    case MILLI_LITRE
    case LITRE
    case SET_DAILY_WATER_LIMIT
    case WATER_INTAKE_IN_LITRES
    case ADD_DAILY_WATER_LIMIT
    case LANDING_TITLE
    case LANDING_SUBTITLE
    case MARK_COMPLETE
    case MARK_COMPLETE_ALERT
    case INVITE_CODE
    case USE_REFER_CODE
    case CLINIC_ADDRESS
    case ADD_ADDRESS
    case SELECT_DELIVERY_ADDRESS
    case CURRENT_LOCATION
    case LOCATION
    case CLINIC_ALERT_MESSAGE
    case REQUEST_FOR_PAYMENT
    case SUPPORT
    case DOSAGE
    case ML
    case AMOUNT
    case EXTRA_PAYMENT
    case EXTRA_PAYMENT_STATUS_PENDING
    case EXTRA_PAYMENT_STATUS_PAID
    case CANCEL_REASON
    case CANCEL_REASON_ALERT
    case MEDICAL_HISTORY
    case MEDICAL_HISTORY_PLACEHOLDER
    case ESTIMATE_TIME
    case NO_MEDICAL_HISTORY
    case NO_MEDICAL_HISTORY_DESC
        
    case success
    case apiFailure
    case validationFailure
    case notification
    
    case DoseTimingWith_1
    case DoseTimingWith_2
    case DoseTimingWith_3
    
    case DoseTime_1
    case DoseTime_2
    case DoseTime_3
    
    case DoseValue_1
    case DoseValue_2
    case DoseValue_3
    case DoseValue_4
    case DoseValue_5
    
    case SINGLE_DIGIT_DAY
    case MULTI_DIGIT_DAY
    
    case DOSAGE_TYPE_1
    case DOSAGE_TYPE_2
    case DOSAGE_TYPE_3

    case INTRO_1_TITLE
    case INTRO_2_TITLE
    case INTRO_3_TITLE
    case INTRO_4_TITLE
    case INTRO_5_TITLE
    case INTRO_6_TITLE

    case INTRO_1_DESC
    case INTRO_2_DESC
    case INTRO_3_DESC
    case INTRO_4_DESC
    case INTRO_5_DESC
    case INTRO_6_DESC
    
    case HEALTH_TOOL
    case HEALTH_TOOL_01_TITLE
    case HEALTH_TOOL_02_TITLE
    case HEALTH_TOOL_03_TITLE
    case HEALTH_TOOL_04_TITLE
    case HEALTH_TOOL_01_SUBTITLE
    case HEALTH_TOOL_02_SUBTITLE
    case HEALTH_TOOL_03_SUBTITLE
    case HEALTH_TOOL_04_SUBTITLE
    
    case HEIGHT
    case WEIGHT
    case KG
    case CM
    case YOUR_BMI
    case MALE
    case FEMALE
    case OVERWEIGHT
    case NORMAL
    case UNDERWEIGHT
    
    case CALCULATION_METHOD
    case LAST_PERIOD
    case CONCEPTION_DATE
    case IVF
    case ULTRASOUND
    case FIRST_DAY_OF_LAST_PERIOD
    case DATE_OF_CONCEPTION
    case DATE_OF_TRANSFER
    case DATE_OF_ULTRSOUND
    case DATE_ONLY_PLACEHOLDER
    case CYCLE_LENGTH
    case IVF_3_DAY
    case IVF_5_DAY
    case ULTRASOUND_WEEKS
    case ULTRASOUND_DAYS
    case IVF_TRANSFER_DATE
    case CALUCLATE_DUE_DATE
    case UltrasoundWeek_One
    case UltrasoundWeek_Two
    case UltrasoundWeek_Three
    case UltrasoundWeek_Four
    case UltrasoundWeek_Five
    case UltrasoundWeek_Six
    case UltrasoundWeek_Seven
    case UltrasoundWeek_Eight
    case UltrasoundWeek_Nine
    case UltrasoundWeek_Ten
    case UltrasoundWeek_Eleven
    case UltrasoundWeek_Twelve
    case UltrasoundWeek_Thirteen
    case UltrasoundWeek_Fourteen
    case UltrasoundWeek_Fifteen
    case UltrasoundWeek_Sixteen
    case UltrasoundWeek_Seventeen
    case UltrasoundWeek_Eighteen
    case UltrasoundWeek_Nineteen
    case UltrasoundWeek_Twenty
    case UltrasoundWeek_TwentyOne
    case UltrasoundWeek_TwentyTwo
    case UltrasoundWeek_TwentyThree
    case UltrasoundWeek_TwentyFour
    case UltrasoundDay_Zero
    case UltrasoundDay_One
    case UltrasoundDay_Two
    case UltrasoundDay_Three
    case UltrasoundDay_Four
    case UltrasoundDay_Five
    case UltrasoundDay_Six
    case CycleLength_NA
    case CycleLength_Days_21
    case CycleLength_Days_22
    case CycleLength_Days_23
    case CycleLength_Days_24
    case CycleLength_Days_25
    case CycleLength_Days_26
    case CycleLength_Days_27
    case CycleLength_Days_28
    case CycleLength_Days_29
    case CycleLength_Days_30
    case CycleLength_Days_31
    case CycleLength_Days_32
    case CycleLength_Days_33
    case CycleLength_Days_34
    case CycleLength_Days_35
    case PREGNANCY_SUCCESS
    case DUE_DATE_IS
    case PREGNANCY_TIMELINE
    case TRIMESTER_1
    case TRIMESTER_2
    case TRIMESTER_3
    case TRIMESTER_VALUE
    case ZODIAC
    case TERMS_ALERT
    
    case aries
    case cancer
    case taurus
    case leo
    case gemini
    case virgo
    case libra
    case capricorn
    case scorpio
    case aquarius
    case sagittarius
    case pisces

    case LOC_PERMISSION_DENIED_TITLE
    case LOC_PERMISSION_DENIED_MESSAGE
    #if NurseLynxExpert
    case CALL_NOW
    case NeedSomeHelp
    case NeedMuchHelp
    case CARE_PLAN
    case MARK_DONE_MULTI_LINE
    case MARK_DONE
    case MARK_DONE_ALERT
    case EMERGENCY_CONTACTS

    #elseif CloudDocPro
    case PRE_ASSESMENT
    case ANSWER_SHORT
    #endif
    case NO_CONTACT
    case NO_CONTACT_DESC
    
    case NOTIFY
    case EMERGENCY_ALERT
    case NO
    case EMERYGENCY_TITLE
    case NO_CONTACT_ADDED
    
    var localized: String {
        return NSLocalizedString(self.rawValue, tableName: Configuration.getValue(for: .APP_LOCALIZABLE), comment: "")
    }
}
